python lifeline.py message "Входящее сообщение" 2
python lifeline.py message "Устновк связи" 2
python lifeline.py message "Получение сообщения" 2
python lifeline.py message "Есть кто живой?"
python lifeline.py message "Эта штука работает вообще?"
python lifeline.py message "Меня кто-нибудь слышит?"
python lifeline.py reply "Я вас слышу." "Кто это?"
python lifeline.py message "Да-да, извини! С этого и надо было начинать."
python lifeline.py message "Мне просто не терпелось получить ответ на мой сигнал."
python lifeline.py message "Меня зовут Тейлор. Я.. я космонавт, я был членом экипажа на звездном корабле 'Варя'."
python lifeline.py reply "На той самой 'Варе'?" "Я почему 'был'? Что произошло?"
python lifeline.py message "Наш космический корабль потерпел крушение на какой-то планете. Я понятия не имею, где именно."
python lifeline.py message "Я сумел попасть в аварийную спасательную капсулу, но я не знаю, успел ли кто-то ещё спастись."
python lifeline.py message "Сенсоры на моем скафандре указывают на то, что в здешней атмосфере есть воздух - это уже чудо!"
python lifeline.py message "Но у меня нет с собой ни еды, ни воды. Арсенал запасов в спасательной капсуле самый элементарный."
python lifeline.py message "Я сумел поймать сигнал мобильным передатчиком, но, похоже, ты - единственный, кто оказался в зоне этого сигнала. Во тебе повезо!"
python lifeline.py message "Кто бы ты ни бы и где бы ты ни был!"
python lifeline.py reply "Ты в порядке?" "Ты где?"
python lifeline.py message "Я примерно представляю, что меня выбросило на необитаемую планету."
python lifeline.py message "У черта спроси, он знает где."
python lifeline.py message "'Варя' плавно по эллиптической траектории шла к Тау Кита IV."
python lifeline.py message "Я не знаю, может, мы сбились с курса, и, если да, то неизвестно насколько."
python lifeline.py message "Меня в рубке не было, когда все это произошло."
python lifeline.py message "Колби... Она толкнула меня в спасательную капсулу и убежала посмотреть, кому еще нужна помошь. Такой уж она человек."
python lifeline.py message "А я, наверное, потерял сознание в капсуле от шоке, страха или еще от чего-то, не знаю, просто на какое время я выпал из реальности."
python lifeline.py message "Но, когда я очнулся, я был уже здесь."